description: |+

author:
  name: David Peterson
  email: david@randombits.org
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.2212766
title: filtered noise
color:
  saturation: 0.2279239466879517
  brandStrength: 0.8918076066765934
  rhythmicContrast: 0.507030539913103
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  lightness: 0.3628440224565566
typography_spectrum: 0.5319149
name: Random I/O
